### ISSUE TITLE
To tak na poważnie?

### ISSUE THREAD

**Issue by GotoFinal** [grzegorz2047/PseudoHC#4]
Aktualnie ten projekt przypomina bardziej żart i satyrę niż projekt, sam nie wiem czy jest sens coś pisać...

![Nah](http://i.imgur.com/XSqGtnx.png)

Tylko po co, na co, dlaczego?

Nawet twój stary projekt ma więcej sensu od tego https://github.com/grzegorz2047/OpenGuild2047/

**Comment by grzegorz2047** [comment]
W skrócie, bo mogę. Dlaczego? Czemu nie? Jeżeli mówisz, że jest bez sensu, to przynajmniej będziesz mógł się trochę pośmiać :)
Może być i nawet 1000 pluginów na gildię do Minkrafta, ale akurat ja chcę coś sobie sprawdzić i tyle.

**Comment by MarcinWieczorek** [comment]
```bash
mkdir foo
cd foo
git init
git remote add origin https://github.com/grzegorz2047/PseudoHC.git
git push --force
```

Polecam poprawia wydajność

**Comment by GotoFinal** [comment]
@grzegorz2047 ale ja się poważnie pytam, bo nie wiem czy jest jakiś sens coś doradzić, czy zwyczajnie to tylko troll.

**Comment by grzegorz2047** [comment]
@GotoFinal Ten projekt jest do pisania sobie na live. Jak będzie sensowna ilość funkcjonalności, to jestem otwarty na komentarze. Po prostu testuje sobie niektóre moje pomysły, więc nie ma sensu na razie męczyć się w doradzanie xd

**Comment by KaVzaQ** [comment]
@grzegorz2047 spokojnie, @GotoFinal ma dzisiaj świetny dzień do śmieszkowania z czyjejś pracy kappa 🔢

**Comment by grzegorz2047** [comment]
@KaVzaQ Nie ma problemu, jak chce się pośmiać, to śmiało. Od tego to jest xd

**Comment by GotoFinal** [comment]
@grzegorz2047 to jeszcze gorzej jak z tego się ludzie uczą :<
bo potem powstają takie potworki: https://github.com/grzegorz2047/PseudoHC/blob/master/src/main/java/com/gmail/grzegorz2047/pseudohc/api/util/ItemUtil.java

A złych praktyk itd w tym kodzie nie brakuje, tak jak tutaj:
https://github.com/grzegorz2047/PseudoHC/blob/master/src/main/java/com/gmail/grzegorz2047/pseudohc/PseudoHC.java#L95
Branie tak tylko po stringu to średni pomysł, i ani trochę sensowny, tylko podatne na literówki a do tego trzeba castować.

itd itp... nawet nie wiem po co tutaj jest folder z libkami, .idea i plik projektu, takich rzeczy się nie commituje.

**Comment by ProgrammingWizzard** [comment]
@grzegorz2047 @KaVzaQ poprostu @GotoFinal za dużo przesiaduje na wypoku ( ͡° ʖ̯ ͡°)

**Comment by grzegorz2047** [comment]
@ProgrammingWizzard https://www.youtube.com/watch?v=0x4HCtcw848 xd
@GotoFinal Akurat te api w tym projekcie jest tylko dołączone. Co do drugiego, to rzeczywiście, też mi się nie spodobało castowanie. Dopóki nie dojdę do lepszego pomysłu, to pewnie to zostanie.

**Comment by GotoFinal** [comment]
@grzegorz2047 tyle wyjść, można np... mieć osobne pola do tych pól, bo i tak nigdzie ta mapa nie jest potrzebna, od biedy można zrobić listę do ułatwienia loadAll i innych pierdołek.
Można podawać wartość z enum i typ, lub mieć tylko enum na odwrotnej zasadzie, EnumName.MESSAGES.get(plugin), ale pierwsza opcja najsensowniejsza, cała ta mapka nie ma zastosowania.

**Comment by grzegorz2047** [comment]
@GotoFinal Może trochę poszedłem na grubo xd Ale jak mówiłem wcześniej, ten projekt jest po to, żeby robić dziwne rzeczy xd

**Comment by Thefilippop1PL** [comment]
@MarcinWieczorek turbosmieszność

**Comment by MarcinWieczorek** [comment]
@Thefilippop1PL Ty jeszcze żyjesz?
